version: '3'
services:
  web:
    container_name: tracemap-api
    build: .
    environment:
      - neo4j_url=bolt://neo4j:7687
      - neo4j_username=neo4j
      - neo4j_password=tracemap
      - twitter_token=mFSqdnDxaTgrPJdnQ32dlJeWx
      - twitter_secret=849wDRvLHCWEZpXemd18A1qbfq9NiVQkpE2bFQU9ppxlKPJXzT
    ports:
     - '5000:5000'
    volumes:
     - .:/usr/src/app
  neo4j:
    image: neo4j:3.0
    ports:
      - "17474:7474"
    volumes:
      - ./db/dbms:/data/dbms
